android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=F:/jdk-17-new/jdk-17.0.13+11
android.nonTransitiveRClass=true
android.enableR8.fullMode=false
